apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  DB_HOST: {{ .Release.Name }}-postgres
  DB_NAME: {{ .Values.postgres.env.POSTGRES_DB }}
  DB_USER: {{ .Values.postgres.env.POSTGRES_USER }}
