apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-service
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-service
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: {{ .Release.Name }}-api
