apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment-api
  labels:
    app: {{ .Release.Name }}-deployment-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      initContainers:
        - name: wait-for-migrations
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: Always
          args:
            - job
            - {{ .Release.Name }}-migrations
      containers:
        - image: {{ .Values.container.image }}
          name: web-container
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
            - secretRef:
                name: {{ .Release.Name }}-secret
