ingress:
  host: arch.homework

container:
  image: jennik/otus-hw-2:latest

postgres:
  enabled: true # to disable postgress set it to false
  env:
    POSTGRES_USER: web-user
    POSTGRES_DB: users-db
    POSTGRES_PASSWORD: "12345"
